### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by anuarshaidenov** [Mithi-code/blog-post#1]
@Mithi-code, we've reviewed your code and there are a few issues that we want to address to make it better:
- You should use a separate .css file for your styles since it's a bad practice to have your styles in an .HTML file.
- You should make use of semantic tags for better accessibility
- You should use descriptive class and id names
- You should create a separate folder for your assets such as images for a better structure.

**Comment by Mithi-code** [comment]
### Thanks for your feedback
-I am going to follow these things in future projects
